app:
  name: x---service-slug---x
  type: api
  labels:
    app: x---service-slug---x
    role: api
  volumeMounts:
    - mountPath: /app/config/debugging-user
      name: debugging-user
  resources:
    requests:
      cpu: 100m
      memory: 300Mi
    limits:
      cpu: 200m
      memory: 500Mi
  env:
    - name: NODE_ENV
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: "/app/config/debugging-user/credentials.json"

volumes:
  - name: debugging-user
    secret:
      defaultMode: 420
      secretName: tf-debugging-user

podAntiAffinity: true
