app:
  name: x---service-slug---x
  type: api
  labels:
    app: x---service-slug---x
    role: api
  resources:
    requests:
      cpu: 100m
      memory: 300Mi
    limits:
      cpu: 200m
      memory: 500Mi
  env:
    - name: NODE_ENV
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - x---service-slug---x
      topologyKey: kubernetes.io/hostname
